// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCTM.Server.DataModel;

#nullable disable

namespace TCTM.Server.Migrations
{
    [DbContext(typeof(TctmDbContext))]
    partial class TctmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("TCTM.Server.DataModel.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BlackPlayerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Bracket")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Disputed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReportedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WhitePlayerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlackPlayerId");

                    b.HasIndex("RoundId");

                    b.HasIndex("WhitePlayerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlayerToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "DisplayName")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "RoundNumber")
                        .IsUnique();

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Standing", b =>
                {
                    b.Property<Guid>("TournamentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Buchholz")
                        .HasColumnType("REAL");

                    b.Property<int>("Draws")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Losses")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Points")
                        .HasColumnType("REAL");

                    b.Property<double>("SonnebornBerger")
                        .HasColumnType("REAL");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("TournamentId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Standings");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeControlMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeControlPreset")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique();

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Match", b =>
                {
                    b.HasOne("TCTM.Server.DataModel.Player", "BlackPlayer")
                        .WithMany("BlackMatches")
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TCTM.Server.DataModel.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCTM.Server.DataModel.Player", "WhitePlayer")
                        .WithMany("WhiteMatches")
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BlackPlayer");

                    b.Navigation("Round");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Player", b =>
                {
                    b.HasOne("TCTM.Server.DataModel.Tournament", "Tournament")
                        .WithMany("Players")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Round", b =>
                {
                    b.HasOne("TCTM.Server.DataModel.Tournament", "Tournament")
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Standing", b =>
                {
                    b.HasOne("TCTM.Server.DataModel.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TCTM.Server.DataModel.Tournament", "Tournament")
                        .WithMany("Standings")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Player", b =>
                {
                    b.Navigation("BlackMatches");

                    b.Navigation("WhiteMatches");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TCTM.Server.DataModel.Tournament", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Rounds");

                    b.Navigation("Standings");
                });
#pragma warning restore 612, 618
        }
    }
}
